/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as EnrollmentIndexRouteImport } from './routes/enrollment/index'
import { Route as ProfileStudyPlanRouteImport } from './routes/profile/study-plan'
import { Route as ProfilePersonalRouteImport } from './routes/profile/personal'
import { Route as ProfileDocumentsRouteImport } from './routes/profile/documents'
import { Route as ProfileContactRouteImport } from './routes/profile/contact'
import { Route as ProfileAcademicHistoryRouteImport } from './routes/profile/academic-history'
import { Route as ProfileAcademicRouteImport } from './routes/profile/academic'
import { Route as ManagementTeachersRouteImport } from './routes/management/teachers'
import { Route as ManagementStudentsRouteImport } from './routes/management/students'
import { Route as ManagementPeriodsRouteImport } from './routes/management/periods'
import { Route as ManagementCoursesRouteImport } from './routes/management/courses'
import { Route as FinancePaymentRouteImport } from './routes/finance/payment'
import { Route as FinanceOtherChargesRouteImport } from './routes/finance/other-charges'
import { Route as FinanceHistoryRouteImport } from './routes/finance/history'
import { Route as FinanceAccountRouteImport } from './routes/finance/account'
import { Route as CommunitiesSplatRouteImport } from './routes/communities/$'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/index'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/home'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/feedback'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/documents'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/calendar'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/attendance'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/gaap/index'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/evaluations/index'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review.$gaapId'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review.$id'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit.$id'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const EnrollmentIndexRoute = EnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStudyPlanRoute = ProfileStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileDocumentsRoute = ProfileDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAcademicHistoryRoute = ProfileAcademicHistoryRouteImport.update({
  id: '/academic-history',
  path: '/academic-history',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAcademicRoute = ProfileAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ProfileRoute,
} as any)
const ManagementTeachersRoute = ManagementTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementStudentsRoute = ManagementStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementPeriodsRoute = ManagementPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementCoursesRoute = ManagementCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ManagementRoute,
} as any)
const FinancePaymentRoute = FinancePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceOtherChargesRoute = FinanceOtherChargesRouteImport.update({
  id: '/other-charges',
  path: '/other-charges',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceHistoryRoute = FinanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountRoute = FinanceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => FinanceRoute,
} as any)
const CommunitiesSplatRoute = CommunitiesSplatRouteImport.update({
  id: '/communities/$',
  path: '/communities/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport.update({
    id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteImport.update({
    id: '/_tabs',
    getParentRoute: () =>
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
  } as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport.update(
    {
      id: '/evaluations/new',
      path: '/evaluations/new',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRouteImport.update(
    {
      id: '/home',
      path: '/home',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRouteImport.update(
    {
      id: '/feedback',
      path: '/feedback',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRouteImport.update(
    {
      id: '/documents',
      path: '/documents',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRouteImport.update(
    {
      id: '/calendar',
      path: '/calendar',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRouteImport.update(
    {
      id: '/attendance',
      path: '/attendance',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRouteImport.update(
    {
      id: '/gaap/',
      path: '/gaap/',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRouteImport.update(
    {
      id: '/evaluations/',
      path: '/evaluations/',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRouteImport.update(
    {
      id: '/gaap/review/$gaapId',
      path: '/gaap/review/$gaapId',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRouteImport.update(
    {
      id: '/evaluations/review/$id',
      path: '/evaluations/review/$id',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRouteImport.update(
    {
      id: '/evaluations/edit/$id',
      path: '/evaluations/edit/$id',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/management': typeof ManagementRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/management/courses': typeof ManagementCoursesRoute
  '/management/periods': typeof ManagementPeriodsRoute
  '/management/students': typeof ManagementStudentsRoute
  '/management/teachers': typeof ManagementTeachersRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/attendance': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/calendar': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/documents': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/feedback': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/home': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/management/courses': typeof ManagementCoursesRoute
  '/management/periods': typeof ManagementPeriodsRoute
  '/management/students': typeof ManagementStudentsRoute
  '/management/teachers': typeof ManagementTeachersRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment': typeof EnrollmentIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/management': typeof ManagementIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/attendance': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/calendar': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/documents': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/feedback': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/home': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/management': typeof ManagementRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/management/courses': typeof ManagementCoursesRoute
  '/management/periods': typeof ManagementPeriodsRoute
  '/management/students': typeof ManagementStudentsRoute
  '/management/teachers': typeof ManagementTeachersRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteWithChildren
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/attendance': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/calendar': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/documents': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/feedback': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/home': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/evaluations/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/gaap/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/management'
    | '/profile'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/management/courses'
    | '/management/periods'
    | '/management/students'
    | '/management/teachers'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment/'
    | '/finance/'
    | '/management/'
    | '/profile/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/attendance'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/calendar'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/documents'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/feedback'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/home'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/management/courses'
    | '/management/periods'
    | '/management/students'
    | '/management/teachers'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment'
    | '/finance'
    | '/management'
    | '/profile'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/attendance'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/calendar'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/documents'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/feedback'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/home'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/management'
    | '/profile'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/management/courses'
    | '/management/periods'
    | '/management/students'
    | '/management/teachers'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment/'
    | '/finance/'
    | '/management/'
    | '/profile/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/attendance'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/calendar'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/documents'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/feedback'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/home'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/evaluations/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/gaap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ManagementRoute: typeof ManagementRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CommunitiesSplatRoute: typeof CommunitiesSplatRoute
  EnrollmentIndexRoute: typeof EnrollmentIndexRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/enrollment/': {
      id: '/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof EnrollmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/study-plan': {
      id: '/profile/study-plan'
      path: '/study-plan'
      fullPath: '/profile/study-plan'
      preLoaderRoute: typeof ProfileStudyPlanRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/personal': {
      id: '/profile/personal'
      path: '/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/documents': {
      id: '/profile/documents'
      path: '/documents'
      fullPath: '/profile/documents'
      preLoaderRoute: typeof ProfileDocumentsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/academic-history': {
      id: '/profile/academic-history'
      path: '/academic-history'
      fullPath: '/profile/academic-history'
      preLoaderRoute: typeof ProfileAcademicHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/academic': {
      id: '/profile/academic'
      path: '/academic'
      fullPath: '/profile/academic'
      preLoaderRoute: typeof ProfileAcademicRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/management/teachers': {
      id: '/management/teachers'
      path: '/teachers'
      fullPath: '/management/teachers'
      preLoaderRoute: typeof ManagementTeachersRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/students': {
      id: '/management/students'
      path: '/students'
      fullPath: '/management/students'
      preLoaderRoute: typeof ManagementStudentsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/periods': {
      id: '/management/periods'
      path: '/periods'
      fullPath: '/management/periods'
      preLoaderRoute: typeof ManagementPeriodsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/courses': {
      id: '/management/courses'
      path: '/courses'
      fullPath: '/management/courses'
      preLoaderRoute: typeof ManagementCoursesRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/finance/payment': {
      id: '/finance/payment'
      path: '/payment'
      fullPath: '/finance/payment'
      preLoaderRoute: typeof FinancePaymentRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/other-charges': {
      id: '/finance/other-charges'
      path: '/other-charges'
      fullPath: '/finance/other-charges'
      preLoaderRoute: typeof FinanceOtherChargesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/history': {
      id: '/finance/history'
      path: '/history'
      fullPath: '/finance/history'
      preLoaderRoute: typeof FinanceHistoryRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/account': {
      id: '/finance/account'
      path: '/account'
      fullPath: '/finance/account'
      preLoaderRoute: typeof FinanceAccountRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/communities/$': {
      id: '/communities/$'
      path: '/communities/$'
      fullPath: '/communities/$'
      preLoaderRoute: typeof CommunitiesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
      path: '/'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
      path: '/members'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs'
      path: ''
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
      path: '/evaluations/new'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/home': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/home'
      path: '/home'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/home'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/feedback': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/feedback'
      path: '/feedback'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/feedback'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/documents': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/documents'
      path: '/documents'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/documents'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/calendar': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/calendar'
      path: '/calendar'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/calendar'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/attendance': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/attendance'
      path: '/attendance'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/attendance'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/gaap/': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/gaap/'
      path: '/gaap'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/evaluations/': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/_tabs/evaluations/'
      path: '/evaluations'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId'
      path: '/gaap/review/$gaapId'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/gaap/review/$gaapId'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id'
      path: '/evaluations/review/$id'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/review/$id'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id'
      path: '/evaluations/edit/$id'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit/$id'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountRoute: typeof FinanceAccountRoute
  FinanceHistoryRoute: typeof FinanceHistoryRoute
  FinanceOtherChargesRoute: typeof FinanceOtherChargesRoute
  FinancePaymentRoute: typeof FinancePaymentRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountRoute: FinanceAccountRoute,
  FinanceHistoryRoute: FinanceHistoryRoute,
  FinanceOtherChargesRoute: FinanceOtherChargesRoute,
  FinancePaymentRoute: FinancePaymentRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ManagementRouteChildren {
  ManagementCoursesRoute: typeof ManagementCoursesRoute
  ManagementPeriodsRoute: typeof ManagementPeriodsRoute
  ManagementStudentsRoute: typeof ManagementStudentsRoute
  ManagementTeachersRoute: typeof ManagementTeachersRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
}

const ManagementRouteChildren: ManagementRouteChildren = {
  ManagementCoursesRoute: ManagementCoursesRoute,
  ManagementPeriodsRoute: ManagementPeriodsRoute,
  ManagementStudentsRoute: ManagementStudentsRoute,
  ManagementTeachersRoute: ManagementTeachersRoute,
  ManagementIndexRoute: ManagementIndexRoute,
}

const ManagementRouteWithChildren = ManagementRoute._addFileChildren(
  ManagementRouteChildren,
)

interface ProfileRouteChildren {
  ProfileAcademicRoute: typeof ProfileAcademicRoute
  ProfileAcademicHistoryRoute: typeof ProfileAcademicHistoryRoute
  ProfileContactRoute: typeof ProfileContactRoute
  ProfileDocumentsRoute: typeof ProfileDocumentsRoute
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileStudyPlanRoute: typeof ProfileStudyPlanRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAcademicRoute: ProfileAcademicRoute,
  ProfileAcademicHistoryRoute: ProfileAcademicHistoryRoute,
  ProfileContactRoute: ProfileContactRoute,
  ProfileDocumentsRoute: ProfileDocumentsRoute,
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileStudyPlanRoute: ProfileStudyPlanRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteChildren {
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute
}

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteChildren: CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteChildren =
  {
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsAttendanceRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsCalendarRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsDocumentsRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsFeedbackRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsHomeRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsEvaluationsIndexRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsGaapIndexRoute,
  }

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteWithChildren =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute._addFileChildren(
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteChildren,
  )

interface CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren {
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteWithChildren
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute
}

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren: CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren =
  {
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberTabsRouteWithChildren,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditIdRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsReviewIdRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberGaapReviewGaapIdRoute,
  }

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute._addFileChildren(
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ManagementRoute: ManagementRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  CommunitiesSplatRoute: CommunitiesSplatRoute,
  EnrollmentIndexRoute: EnrollmentIndexRoute,
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute:
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
