/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CoursiaBackupRouteImport } from './routes/coursia-backup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as EnrollmentIndexRouteImport } from './routes/enrollment/index'
import { Route as ProfileStudyPlanRouteImport } from './routes/profile/study-plan'
import { Route as ProfilePersonalRouteImport } from './routes/profile/personal'
import { Route as ProfileDocumentsRouteImport } from './routes/profile/documents'
import { Route as ProfileContactRouteImport } from './routes/profile/contact'
import { Route as ProfileAcademicHistoryRouteImport } from './routes/profile/academic-history'
import { Route as ProfileAcademicRouteImport } from './routes/profile/academic'
import { Route as FinancePaymentRouteImport } from './routes/finance/payment'
import { Route as FinanceOtherChargesRouteImport } from './routes/finance/other-charges'
import { Route as FinanceHistoryRouteImport } from './routes/finance/history'
import { Route as FinanceAccountRouteImport } from './routes/finance/account'
import { Route as CommunitiesSplatRouteImport } from './routes/communities/$'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/index'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursiaBackupRoute = CoursiaBackupRouteImport.update({
  id: '/coursia-backup',
  path: '/coursia-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const EnrollmentIndexRoute = EnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStudyPlanRoute = ProfileStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileDocumentsRoute = ProfileDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAcademicHistoryRoute = ProfileAcademicHistoryRouteImport.update({
  id: '/academic-history',
  path: '/academic-history',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAcademicRoute = ProfileAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ProfileRoute,
} as any)
const FinancePaymentRoute = FinancePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceOtherChargesRoute = FinanceOtherChargesRouteImport.update({
  id: '/other-charges',
  path: '/other-charges',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceHistoryRoute = FinanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountRoute = FinanceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => FinanceRoute,
} as any)
const CommunitiesSplatRoute = CommunitiesSplatRouteImport.update({
  id: '/communities/$',
  path: '/communities/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport.update({
    id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport.update(
    {
      id: '/evaluations/new',
      path: '/evaluations/new',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRouteImport.update(
    {
      id: '/evaluations/edit',
      path: '/evaluations/edit',
      getParentRoute: () =>
        CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coursia-backup': typeof CoursiaBackupRoute
  '/finance': typeof FinanceRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coursia-backup': typeof CoursiaBackupRoute
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment': typeof EnrollmentIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coursia-backup': typeof CoursiaBackupRoute
  '/finance': typeof FinanceRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/finance/account': typeof FinanceAccountRoute
  '/finance/history': typeof FinanceHistoryRoute
  '/finance/other-charges': typeof FinanceOtherChargesRoute
  '/finance/payment': typeof FinancePaymentRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/profile/academic-history': typeof ProfileAcademicHistoryRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/documents': typeof ProfileDocumentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/study-plan': typeof ProfileStudyPlanRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coursia-backup'
    | '/finance'
    | '/profile'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment/'
    | '/finance/'
    | '/profile/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coursia-backup'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment'
    | '/finance'
    | '/profile'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
  id:
    | '__root__'
    | '/'
    | '/coursia-backup'
    | '/finance'
    | '/profile'
    | '/schedule'
    | '/auth/signin'
    | '/auth/signup'
    | '/communities/$'
    | '/finance/account'
    | '/finance/history'
    | '/finance/other-charges'
    | '/finance/payment'
    | '/profile/academic'
    | '/profile/academic-history'
    | '/profile/contact'
    | '/profile/documents'
    | '/profile/personal'
    | '/profile/study-plan'
    | '/enrollment/'
    | '/finance/'
    | '/profile/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursiaBackupRoute: typeof CoursiaBackupRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CommunitiesSplatRoute: typeof CommunitiesSplatRoute
  EnrollmentIndexRoute: typeof EnrollmentIndexRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coursia-backup': {
      id: '/coursia-backup'
      path: '/coursia-backup'
      fullPath: '/coursia-backup'
      preLoaderRoute: typeof CoursiaBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/enrollment/': {
      id: '/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof EnrollmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/study-plan': {
      id: '/profile/study-plan'
      path: '/study-plan'
      fullPath: '/profile/study-plan'
      preLoaderRoute: typeof ProfileStudyPlanRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/personal': {
      id: '/profile/personal'
      path: '/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/documents': {
      id: '/profile/documents'
      path: '/documents'
      fullPath: '/profile/documents'
      preLoaderRoute: typeof ProfileDocumentsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/academic-history': {
      id: '/profile/academic-history'
      path: '/academic-history'
      fullPath: '/profile/academic-history'
      preLoaderRoute: typeof ProfileAcademicHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/academic': {
      id: '/profile/academic'
      path: '/academic'
      fullPath: '/profile/academic'
      preLoaderRoute: typeof ProfileAcademicRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/finance/payment': {
      id: '/finance/payment'
      path: '/payment'
      fullPath: '/finance/payment'
      preLoaderRoute: typeof FinancePaymentRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/other-charges': {
      id: '/finance/other-charges'
      path: '/other-charges'
      fullPath: '/finance/other-charges'
      preLoaderRoute: typeof FinanceOtherChargesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/history': {
      id: '/finance/history'
      path: '/history'
      fullPath: '/finance/history'
      preLoaderRoute: typeof FinanceHistoryRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/account': {
      id: '/finance/account'
      path: '/account'
      fullPath: '/finance/account'
      preLoaderRoute: typeof FinanceAccountRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/communities/$': {
      id: '/communities/$'
      path: '/communities/$'
      fullPath: '/communities/$'
      preLoaderRoute: typeof CommunitiesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
      path: '/'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
      path: '/members'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/members'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
      path: '/evaluations/new'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/new'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'
      path: '/evaluations/edit'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber/evaluations/edit'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRouteImport
      parentRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountRoute: typeof FinanceAccountRoute
  FinanceHistoryRoute: typeof FinanceHistoryRoute
  FinanceOtherChargesRoute: typeof FinanceOtherChargesRoute
  FinancePaymentRoute: typeof FinancePaymentRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountRoute: FinanceAccountRoute,
  FinanceHistoryRoute: FinanceHistoryRoute,
  FinanceOtherChargesRoute: FinanceOtherChargesRoute,
  FinancePaymentRoute: FinancePaymentRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ProfileRouteChildren {
  ProfileAcademicRoute: typeof ProfileAcademicRoute
  ProfileAcademicHistoryRoute: typeof ProfileAcademicHistoryRoute
  ProfileContactRoute: typeof ProfileContactRoute
  ProfileDocumentsRoute: typeof ProfileDocumentsRoute
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileStudyPlanRoute: typeof ProfileStudyPlanRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAcademicRoute: ProfileAcademicRoute,
  ProfileAcademicHistoryRoute: ProfileAcademicHistoryRoute,
  ProfileContactRoute: ProfileContactRoute,
  ProfileDocumentsRoute: ProfileDocumentsRoute,
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileStudyPlanRoute: ProfileStudyPlanRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren {
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute
}

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren: CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren =
  {
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberMembersRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberIndexRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsEditRoute,
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute:
      CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberEvaluationsNewRoute,
  }

const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute._addFileChildren(
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursiaBackupRoute: CoursiaBackupRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  CommunitiesSplatRoute: CommunitiesSplatRoute,
  EnrollmentIndexRoute: EnrollmentIndexRoute,
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute:
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
